from pyautogui import *
import pyautogui
import time
import keyboard
import numpy as np
import random
import win32api, win32con

time.sleep(0.2)
keyboard.press('a')
time.sleep(0.4)
keyboard.release('a')
time.sleep(1.5)
keyboard.press('s')
time.sleep(0.4)
keyboard.release('s')
time.sleep(1.5)
keyboard.press('d')
time.sleep(0.4)
keyboard.release('d')
time.sleep(1.5)
keyboard.press('w')
time.sleep(0.4)
keyboard.release('w')
# 1 set
time.sleep(1.5)
keyboard.press('a')
time.sleep(0.4)
keyboard.release('a')
keyboard.press('shift')
time.sleep(1.5)
keyboard.release('shift')
keyboard.press('s')
time.sleep(0.4)
keyboard.release('s')
time.sleep(1.5)
keyboard.press('d')
time.sleep(0.4)
keyboard.release('d')
keyboard.press('shift')
time.sleep(1.5)
keyboard.release('shift')
keyboard.press('w')
time.sleep(0.4)
keyboard.release('w')
# 2 set
time.sleep(1.5)
keyboard.press('a')
time.sleep(0.4)
keyboard.release('a')
keyboard.press('shift')
time.sleep(1.5)
keyboard.release('shift')
keyboard.press('s')
time.sleep(0.4)
keyboard.release('s')
time.sleep(1.5)
keyboard.press('d')
time.sleep(0.28)
keyboard.release('d')
keyboard.press('shift')
time.sleep(1.5)
keyboard.release('shift')
keyboard.press('w')
time.sleep(0.4)
keyboard.release('w')
# 3 set
time.sleep(1.5)
keyboard.press('a')
time.sleep(0.3)
keyboard.release('a')
keyboard.press('shift')
keyboard.press('space')
time.sleep(1.8)
keyboard.release('space')
keyboard.release('shift')
keyboard.press('s')
time.sleep(0.45)
keyboard.release('s')
keyboard.press('space')
time.sleep(1.5)
keyboard.release('space')
keyboard.press('d')
time.sleep(0.55)
keyboard.release('d')
keyboard.press('shift')
time.sleep(1.5)
keyboard.release('shift')
keyboard.press('w')
time.sleep(0.4)
keyboard.release('w')
# 4 set
time.sleep(1.5)
keyboard.press('a')
time.sleep(0.3)
keyboard.release('a')
keyboard.press('shift')
keyboard.press('space')
time.sleep(1.8)
keyboard.release('space')
keyboard.release('shift')
keyboard.press('s')
time.sleep(0.45)
keyboard.release('s')
keyboard.press('space')
time.sleep(1.5)
keyboard.release('space')
keyboard.press('d')
time.sleep(0.55)
keyboard.release('d')
keyboard.press('shift')
time.sleep(1.5)
keyboard.release('shift')
keyboard.press('w')
time.sleep(0.4)
keyboard.release('w')